function varargout = AnalyzeFreeSwims(procData,varargin)
%AnalyzeFreeSwims Given procData.mat generated by SlowSwim, returns some
%   useful info after analyzing swims
% out = AnalyzeFreeSwims(procData,'fps',fps,'nFramesInTrl',nFramesInTrl);
% 
% Avinash Pujala, Koyama lab/HHMI, 2016

fps = 500;
nFramesInTrl = 750;
preStimPeriod = 0.1;

for jj = 1:numel(varargin)
    if ischar(varargin{jj})
        switch lower(varargin{jj})
            case 'fps'
                fps = varargin{jj+1};
            case lower('nFramesInTrl')
                nFramesInTrl = 
        end
    end
end

disp('Reading tail curvature data from procData...')
tic
tailCurv = procData.tailCurv;
toc
time = (0:size(tailCurv,3)-1)*(1/fps);

end

