function data_cell = CreateCellArray(data, dataMat)
%CreateCellArray - Given data, and dataMat generated by
%ReadSwimDataFromPaths returns a xls type array that can easily be written
%as .csv for later access from R
% data_cell = CreateCellArray(data,dataMat);


paramNames = fieldnames(data.abl.vib{1})';
for paramNum = 1:length(paramNames)
    paramNames{paramNum}(1) = upper(paramNames{paramNum}(1));
end
data_cell ={'AblationType', 'AblationBool','StimType','FishNum','TrlNum','BendNum'};
data_cell = [data_cell, paramNames];
% data_cell = [data_cell, 'SessionNum'];
ablationType = data.ablationType;
ablationType(strfind(ablationType, ' '))=[];
ablatedOrNotGrps = {'abl','ctrl'};
totalFishCount = 0;
sessionCount = 0;
abGrpNum = 0;
tic
for abGrp = ablatedOrNotGrps
    abGrpNum  = abGrpNum + 1;
    disp(abGrp{1});
    if strcmpi(abGrp{1},'abl')
        ablatedBool = true;
    elseif strcmpi(abGrp{1},'ctrl')
        ablatedBool = false;
    end
    var = data.(abGrp{1});
    stimTypes = fieldnames(var);
    for ss = 1:length(stimTypes) 
        if ss ==1
            fishCountFlag= false;
        else
            fishCountFlag = true;
        end
        stimType = stimTypes{ss};
        disp(stimType)
        var = data.(abGrp{1}).(stimType);
        sessionCount = sessionCount + 1;
        for fishNum  = 1:length(var)
            totalFishCount = totalFishCount + 1;
            disp(['Fish #' num2str(fishNum)])
            if ss == 2 && fishCountFlag
                totalFishCount = 1;
                fishCountFlag = false;
            end            
            var = data.(abGrp{1}).(stimType){fishNum};
            params = fieldnames(var);
            inds = strfind(params,'onset');
            ind = [];
            for ii = 1:length(inds)
                if ~isempty(inds{ii})
                    ind = ii;
                end
            end
            sessionNum = var.sessionNum;
            for paramNum = 1:length(params)
                param = params{paramNum};                
                disp(param)
                var = data.(abGrp{1}).(stimType){fishNum}.(param);
                for trlNum = 1:length(var)
                    if iscell(var)
                        var_bend = var{trlNum};
                        var_bend(var_bend ==0)= nan;
                    else
                        var_bend = var;
                        var_bend(var_bend==0) = nan; 
                    end
                    if size(data_cell,1)==1
                        valArray = cell(1,length(params));
                    end
                    valArray{paramNum} = [valArray{paramNum};  var_bend(:)];
                    if ~isempty(var_bend)
                        for bendNum = 1:length(var_bend)
                           if bendNum == 1
                               currentOnset = data.(abGrp{1}).(stimType){fishNum}.onset(trlNum);
                           end
                            paramVals = squeeze(dataMat(abGrpNum,ss,fishNum,:,trlNum,bendNum));
                            paramVals = paramVals(:)';
                            valArray = cell(size(paramVals));
                            for ii = 1:length(valArray)
                                valArray{ii} = paramVals(ii);
                            end
                            valArray{ind} = currentOnset;
                            valArray{end} = sessionNum;
                            data_line = [{ablationType,ablatedBool,stimType,fishNum,trlNum,bendNum}, valArray];
                            data_cell = [data_cell; data_line];
                        end
                    else
                        paramVals = nan(1,length(params));
                        valArray = cell(size(paramVals));
                        for ii = 1:length(valArray)
                            valArray{ii} = paramVals(ii);
                        end
                        valArray{end} = sessionNum;
                        bendNum = nan;
                        data_line = [{ablationType,ablatedBool,stimType,fishNum,trlNum,bendNum}, valArray];
                        data_cell = [data_cell; data_line];
                    end                    
                end
            end
        end
    end    
end
toc

end

