function hOr = GetHeadOrientationFromTailCurv(tailCurv,varargin)
%GetHeadOrientationFromTailCurv Given the 3 dimensional tailCurv variable 
%   generated by SlowSwim.m and related scripts, along with some optional
%   variables, returns the absolute head orientation of the fish.
% headOrientation = GetHeadOrientationFromTailCurv(tailCurv);
% headOrientation =
%   GetHeadOrienationFromTailCurv(tailCurv,lenOfHeadSeg);
% Inputs:
% tailCurv - 3D matrix generated by SlowSwim and related scripts, where 1st
%   dim is rostrocaudal position along the body, 2nd dim are the x, and y
%   coordinates of this position, and the 3rd dim is frame #.
% lenOfHeadSeg - Length of head segment to use for estimating head
%   orientation
% 
% Avinash Pujala, Koyama lab/HHMI

lenOfHeadSeg = 5;
theta = @(v1,v2) acos(dot(v1,v2)/(norm(v1)*norm(v2)))* pi/180;
Complexify = @(v) v(1) + v(2)*1i;
if nargin == 2
    lenOfHeadSeg = varargin{1}; 
    lenOfHeadSeg = min(lenOfHeadSeg, size(tailCurv,1));
end

nTimePts = size(tailCurv,3);
hOr = zeros(nTimePts,1);
hOr_conj = hOr;
v_1 =  [tailCurv(lenOfHeadSeg,1,1),tailCurv(lenOfHeadSeg,2,1)] - [tailCurv(1,1,1),tailCurv(1,2,1)];
hOr(1) = angle(v_1(1) + v_1(2)*1i)*180/pi;
hOr_conj(1) = angle(Complexify(v_1))*180/pi;
for tt = 2:nTimePts
    if tt ~=2
      v_1 = [tailCurv(lenOfHeadSeg,1,tt-1),tailCurv(lenOfHeadSeg,2,tt-1)] - [tailCurv(1,1,tt-1),tailCurv(1,2,tt-1)];
    end
    v_2 = [tailCurv(lenOfHeadSeg,1,tt),tailCurv(lenOfHeadSeg,2,tt)] - [tailCurv(1,1,tt),tailCurv(1,2,tt)];
    hOr(tt) = theta(v_1,v_2);        
    if ~isreal(hOr(tt)) % This happens when when v_1 and v_2 are the same, resulting in acos(1), which gives complex value
        hOr(tt)=0;
    end
    hOr_conj(tt) = angle(Complexify(v_1) * conj(Complexify(v_2)))*180/pi;     
end
hOr_conj(hOr_conj>90) = mod(hOr_conj(hOr_conj>90),90);
hOr_conj(hOr_conj<-90) = mod(hOr_conj(hOr_conj<-90),-90);

blah = hOr;
blah_conj = hOr_conj;

hOr = cumsum(hOr);
hOr_conj = cumsum(hOr_conj);

hOr = hOr_conj;

end

