
function PlotWTs(W)

traceType = W.traceType;
if strcmpi(traceType,'headTail')
    PlotWTs_headTail(W);
elseif strcmpi(traceType,'curv')
    PlotWTs_curv(W);
elseif strcmpi(traceType,'both')
    PlotWTs_headTail(W);
     PlotWTs_curv(W);
end


function PlotWTs_headTail(W)
%% Given W generated by GetFishWaves_fish or GetFishWaves_group, plots all WTs from all trials in a fish
trlList = W.trlList;
t = W.time;
freq = W.freq;
cLim = W.cLim;
cLim_avg = [cLim(1) cLim(2)*0.7];
cLim_std = [0 10];
ax = {};
ax{1} = [1 0.39 0 0.61];
ax{2} = [1 0.39 0 0.21];
ax{3} = [1 0.2 0 0];
count = 0;
for trl = trlList(:)'
    count = count + 1;
    fh = figure('Name','Wavelet transforms of orientation timeseries');
    axH = CreateSubaxes(fh,ax{1},ax{2},ax{3});
    % -- Head wavelet --
    axes(axH(1));
    imagesc(t,freq,abs(W.head.coeff{count}))
    set(gca,'ydir','normal','xtick',[],'clim',cLim);
    ylabel({'Head';' Freq (Hz)'})
    xlim([t(1) t(end)])
    title(['Head and tail orientation, trl = ' num2str(trl)])
    box off
    
    % -- Tail wavelet --
    axes(axH(2));
    imagesc(t, freq,abs(W.tail.coeff{count}))
    set(gca,'ydir','normal','xtick',[],'clim',cLim);
    ylabel({'Tail' ; 'Freq (Hz)'})
    xlim([t(1) t(end)])
    
    % -- Head and tail orientation timeseries
    axes(axH(3))
    plot(t,W.head.ts{count},'g.')
    hold on
    plot(t,W.tail.ts{count},'m.')
    xlim([t(1) t(end)])
    ylim([-200 200])
    box off
    ylabel({'Orientation'; '(deg)'})
    xTick = get(gca,'xtick');
    xTick(mod(xTick,100)~=0)=[];
    set(gca,'tickdir','out','xtick',xTick,'ytick',[-100 0 100],'color','k')
    xlabel('Time (ms)')
    shg
    linkaxes(axH,'x');
end
% -- Avg head and tail --
fh = figure('Name','Avg WT for head and tail');
ax{1} =[0.8 0.4 0 0.6];
ax{2} = [0.2 0.4 0.8 0.6];
ax{3} = [0.8 0.4 0 0.2];
ax{4} = [0.2 0.4 0.8 0.2];
ax{5} = [0.8 0.2 0 0];
axH = CreateSubaxes(fh,ax{1},ax{2},ax{3},ax{4},ax{5});
axes(axH(1))
imagesc(t, freq,abs(W.head.avg))
set(gca,'ydir','normal','xtick',[],'clim',cLim_avg);
ylabel({'Head' ; 'Freq (Hz)'})
xlim([t(1) t(end)])
title('Avg WT for head and tail orientation')

axes(axH(2))
plot(mean(abs(W.head.avg),2),freq,'g')
ylim([freq(end) freq(1)])
box off
xlim([-inf inf])
set(gca,'ytick',[],'xaxislocation','top','color','k')

axes(axH(3))
imagesc(t, freq, abs(W.tail.avg))
set(gca,'ydir','normal','xtick',[],'clim',cLim_avg);
ylabel({'Tail' ; 'Freq (Hz)'})
xlim([t(1) t(end)])

axes(axH(4))
plot(mean(abs(W.tail.avg),2),freq,'m')
box off
ylim([freq(end) freq(1)])
xlim([-inf inf])
set(gca,'ytick',[],'color','k')
xlabel('$\Sigma$ power','interpreter','latex')

axes(axH(5))
y = Standardize(mean(abs(W.tail.avg),1)) - Standardize(mean(abs(W.head.avg),1));
plot(t,y,'r')
hold on
plot(t, zeros(size(t)),'y--')
box off
set(gca,'tickdir','out','color','k','xtick',xTick)
xlim([t(1) t(end)])
ylim([-inf inf])
xlabel('Time(ms)')
ylabel('$\Sigma |T| - \Sigma |H|$','interpreter','latex')


% -- Std head and tail --
fh = figure('Name','Std/Mean WT for head and tail');
ax{1} =[0.8 0.4 0 0.6];
ax{2} = [0.2 0.4 0.8 0.6];
ax{3} = [0.8 0.4 0 0.2];
ax{4} = [0.2 0.4 0.8 0.2];
ax{5} = [0.8 0.2 0 0];
axH = CreateSubaxes(fh,ax{1},ax{2},ax{3},ax{4},ax{5});
axes(axH(1))
M_head = abs(W.head.std)./(abs(W.head.avg)+1);
imagesc(t, freq,M_head)
set(gca,'ydir','normal','xtick',[],'clim',cLim_std);
ylabel({'Head' ; 'Freq (Hz)'})
xlim([t(1) t(end)])
title('Std/Mean WT for head and tail orientation')

axes(axH(2))
plot(mean(M_head,2),freq,'g')
ylim([freq(end) freq(1)])
box off
xlim([-inf inf])
set(gca,'ytick',[],'xaxislocation','top','color','k')

axes(axH(3))
M_tail = abs(W.tail.std)./(abs(W.tail.avg)+1);
imagesc(t, freq, M_tail)
set(gca,'ydir','normal','xtick',[],'clim',cLim_std);
ylabel({'Tail' ; 'Freq (Hz)'})
xlim([t(1) t(end)])

axes(axH(4))
plot(mean(M_tail,2),freq,'m')
box off
ylim([freq(end) freq(1)])
xlim([-inf inf])
set(gca,'ytick',[],'color','k')
xlabel('$\Sigma$ power','interpreter','latex')

axes(axH(5))
y = Standardize(mean(M_tail,1)) - Standardize(mean(M_head,1));
plot(t,y,'r')
hold on
plot(t, zeros(size(t)),'y--')
box off
set(gca,'tickdir','out','color','k','xtick',xTick)
xlim([t(1) t(end)])
ylim([-inf inf])
xlabel('Time(ms)')
ylabel('$\Sigma |T| - \Sigma |H|$','interpreter','latex')
end

function PlotWTs_curv(W)
%% Given W generated by GetFishWaves_fish or GetFishWaves_group, plots all WTs from all trials in a fish
trlList = W.trlList;
t = W.time;
freq = W.freq;
cLim = W.cLim;
cLim_avg = [cLim(1) cLim(2)*0.7];
cLim_std = [0 10];
ax = {};
ax{1} = [1 0.59 0 0.41]; % Wavelet axes
ax{2} = [1 0.2 0 0.205]; % Timeseries axes
ax{3} = [1 0.2 0 0]; % Instantaneous mean freq and angular velocity axes
gKer = gausswin(12); gKer = gKer/sum(gKer);
angVel_all = [];
count = 0;
for trl = trlList(:)'
    count = count + 1;
    fh = figure('Name','Wavelet transforms of body curvature timeseries');
    axH = CreateSubaxes(fh,ax{1},ax{2},ax{3});
    % -- Curv wavelet --
    axes(axH(1));
    imagesc(t,freq,abs(W.curv.coeff{count}))
    set(gca,'ydir','normal','xtick',[],'clim',cLim);
    ylabel({'Curvature';' Freq (Hz)'})
    xlim([t(1) t(end)])
    title(['Body curvature, trl = ' num2str(trl)])
    box off
        
    % -- Curvature timeseries
    axes(axH(2))
    plot(t,W.curv.ts{count},'g.')
    xlim([t(1) t(end)])
    ylim([-300 300])
    box off
    ylabel({'Curvature'; '(deg)'})
    xTick = get(gca,'xtick');
    xTick(mod(xTick,100)~=0)=[];
    set(gca,'tickdir','out','xtick',xTick,'ytick',[-100 0 100],'color','k')
    
    axes(axH(3))
    mf = instantaneouswavefreq(W.curv.coeff{count},W.freq);
    mp = zscore(instantaneouswavepow(W.curv.coeff{count}));
    mf(mp < 1e-3) = nan;
    plot(t,mf,'m.')
    xlim([t(1) t(end)]);
    ylim(W.freqRange);
    ylabel('Instaneous Freq (Hz)')
    hold on
    angVel = Standardize(conv2(abs(gradient(W.curv.ts{count})),gKer,'same'));
    if count == 1
        angVel_all = angVel;
    else
        angVel_all = [angVel_all; angVel];
    end
    plot(t,angVel*max(mf),'c.-')
    set(gca,'color','k','tickdir','out')
    box off
    xlabel('Time (ms)')
    lh =legend('Mean freq','Ang vel');
    set(lh,'location','best','color',[0.5 0.5 0.5])
    shg
    linkaxes(axH,'x');
end
% -- Avg head and tail --
fh = figure('Name','Avg WT for head and tail');
ax{1} =[0.8 0.8 0 0.2]; % Average wavelet axes
ax{2} = [0.2 0.8 0.8 0.2]; % Total power spectrum axes
ax{3} = [0.8 0.2 0 0];

axH = CreateSubaxes(fh,ax{1},ax{2}, ax{3});
axes(axH(1))
imagesc(t, freq,abs(W.curv.avg))
set(gca,'ydir','normal','xtick',[],'clim',cLim_avg);
ylabel({'Curv' ; 'Freq (Hz)'})
title('Avg WT for curvatures')
set(gca,'tickdir','out','color','k','xtick',xTick)
xlim([t(1) t(end)])
xlabel('Time(ms)')

axes(axH(2))
plot(mean(abs(W.curv.avg),2),freq,'g')
ylim([freq(end) freq(1)])
box off
xlim([-inf inf])
set(gca,'ytick',[],'xaxislocation','top','color','k')
linkaxes(axH,'y')

axes(axH(3))
mf = instantaneouswavefreq(W.curv.avg,W.freq);
mp = zscore(instantaneouswavepow(W.curv.avg));
mf(mp < 1e-3) = nan;
hold on
for trl = 1:size(angVel_all,1)
    plot(t,angVel_all(trl,:)*max(mf),'c-');
end
set(gca,'color','k','tickdir','out')
hold on
plot(t,mf,'m.')
box off
xlim([t(1) t(end)]);
ylim(W.freqRange);
xlabel('Time (ms)')
ylabel('Freq (Hz)/Ang vel')
% lh =legend('Mean freq','Ang vel');
set(lh,'location','best','color',[0.5 0.5 0.5])
shg
linkaxes(axH([1 3]),'x');

% -- Std head and tail --
fh = figure('Name','Std/Mean WT for head and tail');
ax{1} =[0.8 1 0 0]; % Std wavelet axes
ax{2} = [0.2 1 0.8 0]; % Total power spectrum axes

axH = CreateSubaxes(fh,ax{1},ax{2});
axes(axH(1))
M_head = abs(W.curv.std)./(abs(W.curv.avg)+1);
imagesc(t, freq,M_head)
set(gca,'ydir','normal','xtick',[],'clim',cLim_std);
ylabel({'Head' ; 'Freq (Hz)'})
xlim([t(1) t(end)])
title('Std/Mean WT for curvature')

axes(axH(2))
plot(mean(M_head,2),freq,'g')
ylim([freq(end) freq(1)])
box off
xlim([-inf inf])
set(gca,'ytick',[],'xaxislocation','top','color','k')

end

end


